export const topics = {
    programming: [
        'Java',
        'Python',
        'C++',
        'Ruby',
        'JavaScript',
        'PHP',
        'Dart',
    ],
    web: [
        'Random',
        'HTML',
        'CSS',
        'React',
        'Angular',
        'Next.js',
        'Responsive Design',
        'API',
        'Web Security',
    ],
    database: [
        'Random',
        'SQL',
        'RDBMS',
        'NoSQL databases',
        'Database Normalization',
        'Data Warehousing',
        'Data Mining',
    ],
    networking: [
        'Random',
        'Internet Protocol',
        'Transmission Control Protocol',
        'OSI Model',
        'Routing and Switching',
        'Network Securitys',
        'Wireless Networking',
        'VPN',
        'DNS',
    ],
    sdlc: [
        'Random',
        'Agile',
        'Waterfall',
        'Scrum',
        'Kanban',
        'DevOps',
        'Lean Software Development',
    ],
    cloud: [
        'Random',
        'Infrastructure as a Service (IaaS)',
        'Platform as a Service (PaaS)',
        'Software as a Service (SaaS',
        'Cloud Deployment Models',
        'Cloud Security',
        'Cloud Storage',
        'Serverless Computing',
    ],
    ml: [
        'Random',
        'Basic Concepts',
        'Supervised Learning',
        'Unsupervised Learning',
        'Neural Networks',
        'Natural Language Processing',
        'Computer Vision',
        'Deep Learning',
    ],

}
